# .github/worflows/exemple.yml
name: Workflow de test
on: [pull_request, push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Le job a Ã©tÃ© dÃ©clenchÃ© par l'Ã©vÃ©nement ''${{ github.event_name }}''."
      - run: echo "ğŸ§ Le job est lancÃ© sur le serveur ''${{ runner.os }}'' mis Ã  disposition par GitHub!"
      - run: echo "ğŸ” Le nom de la branche est ''${{ github.ref }}'' et celui du dÃ©pÃ´t est ''${{ github.repository }}''."
      - name: Prendre seulement le dernier commit
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ Le dÃ©pÃ´t ''${{ github.repository }}'' a Ã©tÃ© clÃ´nÃ© dans l'environnement mis Ã  disposition."
      - run: echo "ğŸ–¥ï¸ On peut donc commencer Ã  tester notre application..."
      - name: Lister les fichier disponibles dans le dÃ©pÃ´t
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ Statut du job ... ''${{ job.status }}'' !"